name: Prek checks
on: [push, pull_request]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # https://github.com/j178/prek-action
      - uses: j178/prek-action@v2
